# $schema: https://raw.githubusercontent.com/flatpak/flatpak-builder/main/data/flatpak-manifest.schema.json

id: com.beeper.Beeper
runtime: org.freedesktop.Platform
runtime-version: "26.08"
sdk: org.freedesktop.Sdk
base: org.chromium.Chromium.BaseApp
base-version: "26.08"
command: beepertexts

finish-args:
  - --share=ipc
  - --share=network
  - --socket=x11
  - --socket=wayland
  - --socket=pulseaudio
  - --device=dri
  - --filesystem=xdg-download
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=org.freedesktop.secrets

modules:
  - name: beeper
    buildsystem: simple
    build-commands:
      - chmod +x beeper.AppImage
      - ./beeper.AppImage --appimage-extract
      # Install AppImage
      - mkdir -p /app/beeper
      - cp -a squashfs-root/. /app/beeper/
      - rm -rf /app/beeper/AppRun /app/beeper/beepertexts.{desktop,png} /app/beeper/usr/share
      - install -Dm755 beeper.sh /app/bin/beepertexts
      # Copy Resources
      - cp -a squashfs-root/usr/lib /app/lib
      - install -Dm644 squashfs-root/usr/share/icons/hicolor/512x512/apps/beepertexts.png /app/share/icons/hicolor/512x512/apps/com.beeper.Beeper.png
      # Install desktop file
      - install -Dm644 squashfs-root/beepertexts.desktop /app/share/applications/com.beeper.Beeper.desktop
      - desktop-file-edit --set-key=Exec --set-value='beeper.sh %U' --set-icon=com.beeper.Beeper /app/share/applications/com.beeper.Beeper.desktop
    sources:
      - type: file
        path: beeper.AppImage
        dest-filename: beeper.AppImage
      - type: script
        dest-filename: beeper.sh
        commands:
          - export TMPDIR="${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}"
          - export LD_LIBRARY_PATH="/app/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
          - exec zypak-wrapper /app/beeper/beepertexts "$@"
